// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Discount struct {
	Prc                  float32  `protobuf:"fixed32,1,opt,name=prc,proto3" json:"prc,omitempty"`
	ValueInCents         int32    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPrc() float32 {
	if m != nil {
		return m.Prc
	}
	return 0
}

func (m *Discount) GetValueInCents() int32 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int32    `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ProductWithDiscount struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int32     `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductWithDiscount) Reset()         { *m = ProductWithDiscount{} }
func (m *ProductWithDiscount) String() string { return proto.CompactTextString(m) }
func (*ProductWithDiscount) ProtoMessage()    {}
func (*ProductWithDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ProductWithDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductWithDiscount.Unmarshal(m, b)
}
func (m *ProductWithDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductWithDiscount.Marshal(b, m, deterministic)
}
func (m *ProductWithDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductWithDiscount.Merge(m, src)
}
func (m *ProductWithDiscount) XXX_Size() int {
	return xxx_messageInfo_ProductWithDiscount.Size(m)
}
func (m *ProductWithDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductWithDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_ProductWithDiscount proto.InternalMessageInfo

func (m *ProductWithDiscount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductWithDiscount) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *ProductWithDiscount) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProductWithDiscount) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductWithDiscount) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth          int64    `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDateOfBirth() int64 {
	if m != nil {
		return m.DateOfBirth
	}
	return 0
}

type Ids struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID            string   `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Ids) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func init() {
	proto.RegisterType((*Discount)(nil), "product.Discount")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*ProductWithDiscount)(nil), "product.ProductWithDiscount")
	proto.RegisterType((*User)(nil), "product.User")
	proto.RegisterType((*Ids)(nil), "product.Ids")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x49, 0xd2, 0x9f, 0xe4, 0xf6, 0x47, 0x60, 0x10, 0x8a, 0xa0, 0x48, 0x91, 0xc5, 0xd0,
	0x85, 0x0e, 0x65, 0x84, 0xa9, 0x74, 0x20, 0x0b, 0xa0, 0x48, 0x88, 0x31, 0x4a, 0x63, 0x57, 0xb5,
	0xd4, 0xda, 0x91, 0xed, 0x94, 0xf7, 0xe2, 0x09, 0x91, 0x5d, 0x27, 0x02, 0x95, 0x99, 0x2d, 0xe7,
	0xbb, 0xc9, 0x39, 0xc7, 0x37, 0x86, 0x51, 0x25, 0x05, 0xa9, 0x4b, 0x3d, 0xab, 0xa4, 0xd0, 0x02,
	0xf5, 0x9d, 0xc4, 0x0b, 0x08, 0x97, 0x4c, 0x95, 0xa2, 0xe6, 0x1a, 0x9d, 0x42, 0x50, 0xc9, 0x32,
	0xf6, 0x12, 0x6f, 0xea, 0x67, 0xe6, 0x11, 0xdd, 0xc2, 0x78, 0x5f, 0x6c, 0x6b, 0x9a, 0x33, 0x9e,
	0x97, 0x94, 0x6b, 0x15, 0xfb, 0x89, 0x37, 0xed, 0x66, 0x43, 0x4b, 0x53, 0xfe, 0x64, 0x18, 0xfe,
	0x84, 0xfe, 0xdb, 0xc1, 0x0e, 0x8d, 0xc1, 0x67, 0xc4, 0x3a, 0x44, 0x99, 0xcf, 0x88, 0x31, 0xa8,
	0x24, 0x2b, 0x8f, 0x0d, 0x2c, 0x75, 0x06, 0xe8, 0x02, 0xba, 0x9a, 0xe9, 0x2d, 0x8d, 0x03, 0xfb,
	0xe1, 0x41, 0xa0, 0x04, 0x06, 0x84, 0xaa, 0x52, 0xb2, 0x4a, 0x33, 0xc1, 0xe3, 0x8e, 0x9d, 0xfd,
	0x44, 0xf8, 0xcb, 0x83, 0x73, 0x97, 0xfc, 0xc1, 0xf4, 0xa6, 0x3d, 0xc8, 0xbf, 0xb6, 0x40, 0x77,
	0x10, 0x12, 0x97, 0x1c, 0x77, 0x13, 0x6f, 0x3a, 0x98, 0x9f, 0xcd, 0x9a, 0x6d, 0x37, 0x95, 0xb2,
	0xf6, 0x15, 0xbc, 0x87, 0xce, 0xbb, 0xa2, 0xf2, 0xa8, 0xe4, 0x0d, 0xc0, 0x9a, 0x49, 0xa5, 0x73,
	0x5e, 0xec, 0xa8, 0x2d, 0x18, 0x65, 0x91, 0x25, 0x2f, 0xc5, 0x8e, 0xa2, 0x6b, 0x88, 0xb6, 0x45,
	0x33, 0x3d, 0x34, 0x0c, 0x0d, 0xb0, 0x43, 0x0c, 0x23, 0x52, 0x68, 0x9a, 0x8b, 0x75, 0xbe, 0x62,
	0x52, 0x6f, 0x6c, 0xcd, 0x20, 0x1b, 0x18, 0xf8, 0xba, 0x5e, 0x18, 0x84, 0x1f, 0x20, 0x48, 0x89,
	0x42, 0x97, 0xd0, 0xab, 0x15, 0x95, 0xe9, 0xd2, 0x45, 0x3b, 0x85, 0x26, 0x10, 0xb9, 0xd2, 0xe9,
	0xb2, 0x49, 0x6f, 0xc1, 0xfc, 0x19, 0x42, 0xb7, 0x68, 0x85, 0x1e, 0x61, 0xf8, 0x6b, 0xdb, 0xc3,
	0xf6, 0xb4, 0x29, 0x51, 0x57, 0x93, 0x56, 0xfd, 0xf1, 0x67, 0xf0, 0xc9, 0xaa, 0x67, 0x2f, 0xe0,
	0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0xcf, 0x9d, 0x17, 0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	WithDiscount(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*ProductWithDiscount, error)
}

type productsClient struct {
	cc *grpc.ClientConn
}

func NewProductsClient(cc *grpc.ClientConn) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) WithDiscount(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*ProductWithDiscount, error) {
	out := new(ProductWithDiscount)
	err := c.cc.Invoke(ctx, "/product.Products/WithDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	WithDiscount(context.Context, *Ids) (*ProductWithDiscount, error)
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_WithDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).WithDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Products/WithDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).WithDiscount(ctx, req.(*Ids))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WithDiscount",
			Handler:    _Products_WithDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
